### ISSUE TITLE
Fix API inconsistency introduced in #19.

### ISSUE THREAD

**Issue by utkarshkukreti** [utkarshkukreti/select.rs#21]
The speed up is huge, but the usage has become inconsistent. The biggest one is the explicit need to call `.to_selection` when trying to do a `node.find(..).find(..)`: https://github.com/utkarshkukreti/select.rs/commit/c75dba944de4c01185711e0ca94a806ce46704bb#diff-04c6e90faac2675aa89e2176d2eec7d8R34

Another one is the fact that `Selection` does not implement `IntoIterator` (`&Selection` does though) and requires an explicit `&` or `.iter()` before being able to use it in a `for`. Fixing this most likely requires https://github.com/contain-rs/bit-set/issues/11.

These issues need to be fixed before the next version bump.

**Comment by utkarshkukreti** [comment]
One solution is to add a trait that implements all the methods `Selection` has, and implement it for all structs that can be converted into a `Selection`, and make all of those methods automatically convert the struct to a `Selection` and then delegate to the relevant `Selection` method.

I tried to make `Document::find` return a new `document::Find` struct but it's resulting in some ugly code changes:

```diff
-            assert_eq!(document.find(Name("div")).prev().len(), 208);
-            assert_eq!(document.find(Name("div")).next().len(), 203);
-            assert_eq!(document.find(Name("span")).prev().len(), 1729);
-            assert_eq!(document.find(Name("span")).next().len(), 1690);
+            assert_eq!(document.find(Name("div")).into_selection().prev().len(), 208);
+            assert_eq!(document.find(Name("div")).into_selection().next().len(), 203);
+            assert_eq!(document.find(Name("span")).into_selection().prev().len(), 1729);
+            assert_eq!(document.find(Name("span")).into_selection().next().len(), 1690);
```

**Comment by utkarshkukreti** [comment]
Another possible solution is to have different methods that return lazy iterators vs `Selection`s.

**Comment by utkarshkukreti** [comment]
I added [`Child`][1] and [`Descendant`][2] predicates which should reduce the usage of `Selection` (the stackoverflow example does not use `Selection` at all now). Even a naive implementation of `Descendant` is faster than a call to `node::Find::into_selection` and `Selection::find` according to [this bench][3].

[1]: https://github.com/utkarshkukreti/select.rs/commit/5005227dd66d2c3bf32efc90fd1a409eaee9fc14
[2]: https://github.com/utkarshkukreti/select.rs/commit/0479a3bbc7c306ec4f1b65abe70867ed262fb71b
[3]: https://github.com/utkarshkukreti/select.rs/commit/e6cd6622fbc8c6d98ad74ecf8c821015d0e7da51
